### PR TITLE
Password auth: backend

### PR DESCRIPTION
**Pull request by Goose-Of-War**
Changing the backend for the password auth. Kinda yeeted mokshith's branch which had the stuff, so flying blind for now. Will edit the bugs out once I get them from mokshith's local branch :/

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
Record of stuff done till now (so it's easier for me to pick it up and continue)
- Removed some old middleware, like Google Auth and passport (in some places)
- Changed some Schemas so they refer to the password auth: User and Session
- Changed the functions to work with the new models in dbh

To-do: 
- Handler route fixing
- Test pseudo-randomness with this user model
- Pester Mokshith to share the password auth template (I blame Ayush)
- Remove more passport instances or something
- User generation method(?)

**Comment by Goose-Of-War** [comment]
So... I just realised that I can send a POST request using axios and test the routes. Here's me going for it :)

**Comment by PartMan7** [comment]
> So... I just realised that I can send a POST request using axios and test the routes. Here's me going for it :)

Would recommend using an API client like Insomnia or Postman

**Comment by PartMan7** [comment]
Test

**Comment by Goose-Of-War** [comment]
Considering I made the ID numbers to be 21 number char integers, pseudo-randomness should work just fine. ROute fixing can't be done without getting the front-end. Other passport can be yeeted later, so this one seems ready to merge. Lessgo

**Pull request merged**
