### PR TITLE
Fandom quiz (continued)

### PR DESCRIPTION
**Pull request by Goose-Of-War**
We'll be making branches from `fandom-quiz` and making PRs to merge those branches to `fandom-quiz`. Finally, `fandom-quiz` will be merged to `dev` and then `main` after bug fixes.

@nishkalprakash yoroshiku

### CODE REVIEW

**Comment by Goose-Of-War** [comment]
I'll get started on password-auth. @nishkalprakash please finish the front-end 🥲

**Comment by Goose-Of-War** [comment]
Windows...

**Comment by PartMan7** [comment]
...how did that home page make it through

**Comment by Goose-Of-War** [comment]
> ...how did that home page make it through

Because they wanted all details on the landing page itself. Ask the govs

**Comment by Goose-Of-War** [comment]
Will be fixed once we merge PR #11

**Comment by Goose-Of-War** [comment]
And it shan't be merged ig

**Pull request closed without merging**
